<?xml version="1.0"?>
<package format="3">
  <name>arm_bridge</name>
  <version>0.0.1</version>
  <description>ARM ESP32 #2 TCP Bridge</description>
  <maintainer email="jinu@hazardbot.local">jinu</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
